/*
  Warnings:

  - You are about to drop the column `customer_id` on the `OrderDetails` table. All the data in the column will be lost.
  - You are about to drop the column `user_id` on the `OrderDetails` table. All the data in the column will be lost.
  - A unique constraint covering the columns `[email]` on the table `Customer` will be added. If there are existing duplicate values, this will fail.

*/
-- AlterTable
ALTER TABLE "OrderDetails" DROP COLUMN "customer_id",
DROP COLUMN "user_id",
ADD COLUMN     "acc" TEXT,
ADD COLUMN     "catatan_design" TEXT,
ADD COLUMN     "choke" TEXT,
ADD COLUMN     "cutting_bagus" TEXT,
ADD COLUMN     "cutting_mesin" TEXT,
ADD COLUMN     "cutting_reject" TEXT,
ADD COLUMN     "cutting_speed" TEXT,
ADD COLUMN     "dimensi_file" TEXT,
ADD COLUMN     "diskon" TEXT,
ADD COLUMN     "lebar_kain" TEXT,
ADD COLUMN     "no" INTEGER,
ADD COLUMN     "nominal_total" TEXT,
ADD COLUMN     "nospk" INTEGER,
ADD COLUMN     "pet" TEXT,
ADD COLUMN     "power" TEXT,
ADD COLUMN     "press_bagus" TEXT,
ADD COLUMN     "press_mesin" TEXT,
ADD COLUMN     "press_presure" TEXT,
ADD COLUMN     "press_protect" TEXT,
ADD COLUMN     "press_reject" TEXT,
ADD COLUMN     "press_speed" DOUBLE PRECISION,
ADD COLUMN     "press_suhu" TEXT,
ADD COLUMN     "press_waste" TEXT,
ADD COLUMN     "printd_icc" TEXT,
ADD COLUMN     "printd_mesin" TEXT,
ADD COLUMN     "printd_speed" TEXT,
ADD COLUMN     "prints_bagus" TEXT,
ADD COLUMN     "prints_icc" TEXT,
ADD COLUMN     "prints_mesin" TEXT,
ADD COLUMN     "prints_qty" TEXT,
ADD COLUMN     "prints_reject" TEXT,
ADD COLUMN     "prints_target" TEXT,
ADD COLUMN     "prints_waste" TEXT,
ADD COLUMN     "prioritas" TEXT,
ADD COLUMN     "qty_bahan" TEXT,
ADD COLUMN     "qty_cutting" TEXT,
ADD COLUMN     "qty_cutting1" TEXT,
ADD COLUMN     "qty_cutting2" TEXT,
ADD COLUMN     "qty_cutting3" TEXT,
ADD COLUMN     "qty_cutting4" TEXT,
ADD COLUMN     "qty_cutting5" TEXT,
ADD COLUMN     "satuan_bahan" TEXT,
ADD COLUMN     "satuan_cutting" TEXT,
ADD COLUMN     "satuan_cutting1" TEXT,
ADD COLUMN     "satuan_cutting2" TEXT,
ADD COLUMN     "satuan_cutting3" TEXT,
ADD COLUMN     "satuan_cutting4" TEXT,
ADD COLUMN     "satuan_cutting5" TEXT,
ADD COLUMN     "statusprod" TEXT,
ADD COLUMN     "suhu_meja" TEXT,
ADD COLUMN     "tambah_bahan" TEXT,
ADD COLUMN     "tambah_cutting" TEXT,
ADD COLUMN     "tambah_cutting1" TEXT,
ADD COLUMN     "tambah_cutting2" TEXT,
ADD COLUMN     "tambah_cutting3" TEXT,
ADD COLUMN     "tambah_cutting4" TEXT,
ADD COLUMN     "tambah_cutting5" TEXT,
ADD COLUMN     "tambah_produk" TEXT,
ADD COLUMN     "tgl_app_cs" TIMESTAMP(3),
ADD COLUMN     "tgl_app_manager" TIMESTAMP(3),
ADD COLUMN     "tgl_app_prod" TIMESTAMP(3),
ADD COLUMN     "tgl_pengiriman" TIMESTAMP(3),
ADD COLUMN     "total_bahan" TEXT,
ADD COLUMN     "total_cutting" TEXT,
ADD COLUMN     "total_cutting1" TEXT,
ADD COLUMN     "total_cutting2" TEXT,
ADD COLUMN     "total_cutting3" TEXT,
ADD COLUMN     "total_cutting4" TEXT,
ADD COLUMN     "total_cutting5" TEXT,
ADD COLUMN     "total_kain" TEXT,
ADD COLUMN     "total_kertas" TEXT,
ADD COLUMN     "total_pet" TEXT,
ADD COLUMN     "waktu_rip" TIMESTAMP(3),
ADD COLUMN     "white_precentage" TEXT,
ADD COLUMN     "white_setting" TEXT,
ALTER COLUMN "spk" SET DATA TYPE TEXT,
ALTER COLUMN "reject" SET DATA TYPE TEXT,
ALTER COLUMN "panjang_reject" SET DATA TYPE TEXT,
ALTER COLUMN "panjang_order" SET DATA TYPE TEXT,
ALTER COLUMN "lebar_kertas" SET DATA TYPE TEXT,
ALTER COLUMN "marketing" SET DATA TYPE TEXT,
ALTER COLUMN "nominal" SET DATA TYPE TEXT,
ALTER COLUMN "harga_satuan" SET DATA TYPE TEXT,
ALTER COLUMN "keterangan" SET DATA TYPE TEXT,
ALTER COLUMN "invoice" SET DATA TYPE TEXT,
ALTER COLUMN "jenis_pembayaran" SET DATA TYPE TEXT,
ALTER COLUMN "dp" SET DATA TYPE TEXT,
ALTER COLUMN "sisa" SET DATA TYPE TEXT,
ALTER COLUMN "pelunasan" SET DATA TYPE TEXT,
ALTER COLUMN "biaya_tambahan" SET DATA TYPE TEXT,
ALTER COLUMN "status" SET DATA TYPE TEXT,
ALTER COLUMN "statusm" SET DATA TYPE TEXT,
ALTER COLUMN "approval" SET DATA TYPE TEXT,
ALTER COLUMN "approve_mng" SET DATA TYPE TEXT,
ALTER COLUMN "approval_barang" SET DATA TYPE TEXT,
ALTER COLUMN "approval_opr" SET DATA TYPE TEXT,
ALTER COLUMN "rip" SET DATA TYPE TEXT,
ALTER COLUMN "produk" SET DATA TYPE TEXT,
ALTER COLUMN "path" SET DATA TYPE TEXT,
ALTER COLUMN "tf_dp" SET DATA TYPE TEXT,
ALTER COLUMN "tf_pelunasan" SET DATA TYPE TEXT,
ALTER COLUMN "tf_full" SET DATA TYPE TEXT,
ALTER COLUMN "capture" SET DATA TYPE TEXT,
ALTER COLUMN "capture_name" SET DATA TYPE TEXT,
ALTER COLUMN "asal_bahan" SET DATA TYPE TEXT,
ALTER COLUMN "nama_kain" SET DATA TYPE TEXT,
ALTER COLUMN "jumlah_kain" SET DATA TYPE TEXT,
ALTER COLUMN "tipe_produk" SET DATA TYPE TEXT,
ALTER COLUMN "qty" SET DATA TYPE TEXT,
ALTER COLUMN "kategori" SET DATA TYPE TEXT,
ALTER COLUMN "gramasi" SET DATA TYPE TEXT,
ALTER COLUMN "nama_produk" SET DATA TYPE TEXT,
ALTER COLUMN "lebar_file" SET DATA TYPE TEXT,
ALTER COLUMN "no_project" SET DATA TYPE TEXT,
ALTER COLUMN "warna_acuan" SET DATA TYPE TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Customer_email_key" ON "Customer"("email");
