-- PostgreSQL version of order table

CREATE TABLE "order" (
    id BIGSERIAL PRIMARY KEY,
    tanggal DATE,
    spk VARCHAR(10),
    reject VARCHAR(10),
    panjang_reject VARCHAR(10),
    panjang_order VARCHAR(10),
    lebar_kertas VARCHAR(10),
    marketing VARCHAR(10),
    nominal VARCHAR(30),
    harga_satuan VARCHAR(30),
    keterangan VARCHAR(20),
    invoice VARCHAR(30),
    jenis_pembayaran VARCHAR(30),
    dp VARCHAR(30),
    tgl_dp DATE,
    sisa VARCHAR(30),
    pelunasan VARCHAR(30),
    biaya_tambahan VARCHAR(30),
    tgl_lunas DATE,
    tgl_invoice DATE,
    status VARCHAR(20),
    statusm VARCHAR(20),
    approval VARCHAR(20),
    approve_mng VARCHAR(20),
    approval_barang VARCHAR(20),
    approval_opr VARCHAR(20),
    opr_id INTEGER,
    user_id INTEGER,
    print_id INTEGER,
    press_id INTEGER,
    cutting_id INTEGER,
    dtf_id INTEGER,
    penyerahan_id INTEGER,
    designer_id INTEGER,
    manager_id INTEGER,
    customer_id INTEGER,
    rip VARCHAR(20),
    produk VARCHAR(255),
    path VARCHAR(100),
    tf_dp VARCHAR(100),
    tf_pelunasan VARCHAR(100),
    tf_full VARCHAR(100),
    catatan_tf TEXT,
    capture VARCHAR(100),
    capture_name VARCHAR(100),
    asal_bahan VARCHAR(30),
    nama_kain VARCHAR(100),
    jumlah_kain VARCHAR(20),
    tipe_produk VARCHAR(50),
    qty VARCHAR(200),
    kategori VARCHAR(50),
    gramasi VARCHAR(30),
    nama_produk VARCHAR(50),
    catatan TEXT,
    catatan_print TEXT,
    catatan_press TEXT,
    catatan_cutting TEXT,
    lebar_file VARCHAR(255),
    est_order DATE,
    jns_produk_id INTEGER,
    no_project VARCHAR(255),
    tgl_print TIMESTAMP,
    print_done TIMESTAMP,
    tgl_press TIMESTAMP,
    press_done TIMESTAMP,
    tgl_cutting TIMESTAMP,
    cutting_done TIMESTAMP,
    tgl_dtf TIMESTAMP,
    dtf_done TIMESTAMP,
    warna_acuan VARCHAR(255),
    statusprod VARCHAR(255),
    lebar_kain VARCHAR(255),
    prioritas VARCHAR(255),
    prints_mesin VARCHAR(255),
    prints_icc VARCHAR(255),
    prints_target VARCHAR(255),
    dimensi_file VARCHAR(255),
    prints_qty VARCHAR(100),
    total_kertas VARCHAR(255),
    waktu_rip TIME,
    prints_bagus VARCHAR(255),
    prints_reject VARCHAR(255),
    prints_waste VARCHAR(255),
    press_mesin VARCHAR(255),
    press_presure VARCHAR(255),
    press_suhu VARCHAR(255),
    press_speed DOUBLE PRECISION,
    press_protect VARCHAR(255),
    total_kain VARCHAR(255),
    press_bagus VARCHAR(255),
    press_reject VARCHAR(255),
    press_waste VARCHAR(255),
    printd_mesin VARCHAR(255),
    printd_icc VARCHAR(255),
    pet VARCHAR(255),
    suhu_meja VARCHAR(255),
    printd_speed VARCHAR(255),
    white_setting VARCHAR(255),
    choke VARCHAR(255),
    white_precentage VARCHAR(255),
    total_pet VARCHAR(255),
    cutting_mesin VARCHAR(255),
    cutting_speed VARCHAR(255),
    acc VARCHAR(255),
    power VARCHAR(255),
    cutting_bagus VARCHAR(255),
    cutting_reject VARCHAR(255),
    tgl_pengiriman DATE,
    tambah_bahan TEXT,
    tambah_cutting VARCHAR(100),
    tambah_cutting1 VARCHAR(100),
    tambah_cutting2 VARCHAR(100),
    tambah_cutting3 VARCHAR(100),
    tambah_cutting4 VARCHAR(100),
    tambah_cutting5 VARCHAR(100),
    satuan_bahan VARCHAR(100),
    satuan_cutting VARCHAR(100),
    satuan_cutting1 VARCHAR(100),
    satuan_cutting2 VARCHAR(100),
    satuan_cutting3 VARCHAR(100),
    satuan_cutting4 VARCHAR(100),
    satuan_cutting5 VARCHAR(100),
    qty_bahan VARCHAR(100),
    qty_cutting VARCHAR(50),
    qty_cutting1 VARCHAR(50),
    qty_cutting2 VARCHAR(50),
    qty_cutting3 VARCHAR(50),
    qty_cutting4 VARCHAR(50),
    qty_cutting5 VARCHAR(50),
    total_bahan VARCHAR(50),
    total_cutting VARCHAR(50),
    total_cutting1 VARCHAR(50),
    total_cutting2 VARCHAR(50),
    total_cutting3 VARCHAR(50),
    total_cutting4 VARCHAR(50),
    total_cutting5 VARCHAR(50),
    nominal_total VARCHAR(100),
    no INTEGER,
    nospk INTEGER,
    catatan_design TEXT,
    tgl_app_cs TIMESTAMP,
    tgl_app_prod TIMESTAMP,
    tgl_app_manager TIMESTAMP,
    diskon VARCHAR(6),
    tambah_produk VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX idx_order_spk ON "order"(spk);
CREATE INDEX idx_order_customer ON "order"(customer_id);
CREATE INDEX idx_order_status ON "order"(status);

-- Add comments
COMMENT ON TABLE "order" IS 'Order management table for SmartOne ERP';