-- AlterTable
ALTER TABLE "orders" ALTER COLUMN "tgl_print" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "tgl_cutting" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "tgl_dtf" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "tgl_press" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "cutting_done" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "dtf_done" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "press_done" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "print_done" SET DATA TYPE TIMESTAMP(6);
